//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentandrun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public int CarID { get; set; }
        public string Start_date { get; set; }
        public string Start_time { get; set; }
        public string End_date { get; set; }
        public string End_time { get; set; }
        public string Start_place { get; set; }
        public string End_place { get; set; }
        public string TotalAmount { get; set; }
        public string BookingStatus { get; set; }
        public string TransectionID { get; set; }
        public string BookingDate { get; set; }
    
        public virtual Car_details Car_details { get; set; }
        public virtual User User { get; set; }
    }
}
