//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentandrun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car_details()
        {
            this.Bookings = new HashSet<Booking>();
            this.Damage_details = new HashSet<Damage_details>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int CarID { get; set; }
        public string CarNumber { get; set; }
        public string EngineNumber { get; set; }
        public string RegistrationYear { get; set; }
        public string CarDetails { get; set; }
        public string CarImage { get; set; }
        public string Daily_Fee { get; set; }
        public bool IsAvailable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage_details> Damage_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
