//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentandrun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage_details
    {
        public int DamageID { get; set; }
        public int CarID { get; set; }
        public string CarImage_Front { get; set; }
        public string CarImage_Back { get; set; }
        public string CarImage_Right { get; set; }
        public string CarImage_Left { get; set; }
    
        public virtual Car_details Car_details { get; set; }
    }
}
