//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentandrun.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int UserID { get; set; }
        public int CarID { get; set; }
        public string Validation { get; set; }
        public string Comment { get; set; }
    
        public virtual Car_details Car_details { get; set; }
        public virtual User User { get; set; }
    }
}
